### ISSUE TITLE
Can we customize tooltip?

### ISSUE THREAD

**Issue by ahadortiz** [ekeric13/react-star-ratings#11] opened 2018-07-09 22:05 UTC
I think that it's better to provide a function to format tooltip such as '10 point's instead of '1 stars',
'20 points' instead of '2 stars'

**Comment by p11v** [comment] 2018-07-17 18:12
Yes, please, this is essential. If you use a custom SVG or even if your rating system is not 5 points based, this makes no sense.

**Comment by ekeric13** [comment] 2018-07-17 23:52
You can currently do that in this library I made:

https://github.com/ekeric13/react-ratings-declarative

This library is focused on star ratings, but i realized that it would be better if this library was more customizable

https://github.com/ekeric13/react-ratings-declarative#api
`typeOfWidget` prop would do it.

**Comment by ekeric13** [comment] 2018-07-18 00:16
Closing because this is a duplicate of this issue: https://github.com/ekeric13/react-star-ratings/issues/10

**Closed as completed by ekeric13** 2018-07-18 00:16 UTC
